### ISSUE TITLE
More news snippets on the front page?

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb.github.io#13]
Just an idea: On the index page, there is only one latest news entry snippet. What do you think about three, and maybe also a date stamp then? It's just a bit more to see and a better grasp for general activity at first glance.

**Comment by lynxlynxlynx** [comment]
Tried with 2 and a date. Keeps it short, but you see if you missed any news immediately, since we update rarely. Is that fine for you?

**Comment by lynxlynxlynx** [comment]
Eh, I see now the order is not preserved, hmm.

**Comment by MarcelHB** [comment]
I'm fine anyway. Just thought about losing those 20y articles from the frontpage too soon.

From what I see right it looks better, I think. Except the order, yes.

**Comment by lynxlynxlynx** [comment]
I added a workaround, so now the order is correct. I'll add a "20 year" watermark sort of thing to the top image. A new post will happen soon as well, just waiting for the full schedule to be posted first: https://mdco2.mini.debconf.org/
