### ISSUE TITLE
MSVC-build instructions out of date?

### ISSUE THREAD

**Issue by DudeMcDude** [gemrb/gemrb.github.io#15]
https://github.com/gemrb/gemrb.github.io/blob/master/MSVC-build.md

Your appveyor does it with x86, and I saw that you had a lengthy issue getting windows to build where this changed...

**Comment by lynxlynxlynx** [comment]
Appveyor builds 32-bit builds so they also work on 32-bit systems, that's all. Did you actually have some problems building 64-bit?
